FROM nginx:alpine
COPY index.html /usr/share/nginx/html/index.html
COPY mulher-segura.html /usr/share/nginx/html/mulher-segura.html
COPY monitor-sos.html /usr/share/nginx/html/monitor-sos.html
COPY brasao-maringa.png /usr/share/nginx/html/brasao-maringa.png
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
